import type { Metadata } from "next";
import { notFound } from "next/navigation";
import EpisodesSidebar from "./_components/sidebar";
import { getAnilistAnimeDetails } from "@/app/anime/dal";
import { getEpisodesList } from "./dal";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function WatchAnimeLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { id: string; episodeId: string };
}) {
	const { id, episodeId } = await params;
	const [data, animeDetails] = await Promise.all([
		getEpisodesList(id),
		getAnilistAnimeDetails(id),
	]);

	if (!data || !animeDetails) {
		notFound();
	}

	return (
		<>
			<EpisodesSidebar
				episodes={data.data}
				anime={animeDetails.data}
				currentEpisodeId={episodeId}
			>
				{children}
			</EpisodesSidebar>
		</>
	);
}
