import type { Metadata } from "next";
import { notFound } from "next/navigation";
import EpisodesSidebar from "./_components/sidebar";
import { getAnilistAnimeDetails, getHiAnimeDetails } from "@/app/anime/dal";
import { getEpisodesList } from "./dal";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function WatchAnimeLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { id: string; episodeId: string };
}) {
	const { id, episodeId } = await params;
	// const [data, animeDetails] = await Promise.all([
	// 	getEpisodesList(id),
	// 	getAnilistAnimeDetails(id),
	// ]);

	const animeDetails = await getHiAnimeDetails(id);
	if (!animeDetails) {
		notFound();
	}

	return (
		<>
			<EpisodesSidebar
				episodes={animeDetails.data.episodes}
				anime={{
					id: animeDetails.data.hianime.anime.info.id,
					title: animeDetails.data.anilist.title,
				}}
				currentEpisodeId={episodeId}
			>
				{children}
			</EpisodesSidebar>
		</>
	);
}
